#3.6
names=["Shezin","Jamnas","Rizwan"]
print("Hello!,I am keeping a dinner at my house,would you like to come",names[0],"?")
print("\nYo",names[1],"I am planning a dinner night at my place,Make sure are free at that day")
print("\nHello",names[2],"Can you come this weekend for dinner at my place ?")
print("""\nCant come for the dinner!
\t""",names[2])
del names[2]
names.insert(2,"salman")
print("\nHello!,I am keeping a dinner at my house,would you like to come",names[0],"?")
print("\nYo",names[1],"I am planning a dinner night at my place,Make sure are free at that day")
print("\nHello",names[2],"Can you come this weekend for dinner at my place ?")
print("\nWe got a bigger table!")
names.insert(0, 'hadi')
names.insert(2, 'mazin')
names.append('Sufiyan')
print("\n",names[0],"please come to dinner")
print("\n",names[1],"please come to dinner")
print("\n",names[2],"please come to dinner")
print("\n",names[3],"please come to dinner")
print("\n",names[4],"please come to dinner")
print("\n",names[5],"please come to dinner")
print("\nSorry, we can only invite two people to dinner.")
name= names.pop()
print("Sorry, " + name.title() + " there's no room at the table.")
name= names.pop()
print("Sorry, " + name.title() + " there's no room at the table.")
name= names.pop()
print("Sorry, " + name.title() + " there's no room at the table.")
name= names.pop()
print("Sorry, " + name.title() + " there's no room at the table.")
name= names[0].title()
print(name + ", please come to dinner.")
name= names[1].title()
print(name + ", please come to dinner.")
del(names[0])
del(names[0])
print(names)